version: '3.9'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root@123
      - MONGO_INITDB_DATABASE=product-service

volumes:
  mongodb_data: